#!/bin/bash
function usage() {
	printf "
	Usage:
	  cb-cli [options] [arguments]

	Options:
	  -w, --watch
	    Watch a user thar is currently live
	  -d, --download
	    Download a stream from a user that is currently live
	  -s, --subscribe
	    Subscribe to a user
	  -o, --online
	    Show all subbed online users
	  -q, --query
	    Search for streams by tag
	  -c, --config
	    Source a different configuration file
	  -h, --help
	    Display this help message

	Configuration:
	  By default configuration are stored in
	  $XDG_CONFIG_HOME/cb-cli/cb-cli.conf.

	  You can source a different configuration file with
	  the --config flag and specifying a file.
	"
}

if [ $# -eq 0 ]; then
	usage
	exit 1
fi

if [ "$1" != "" ]; then
	case $1 in
	-w | --watch)
		if [ "$2" != "" ]; then
			if curl -s -o /dev/null -w "%{http_code}" https://chaturbate.com/$2/ | grep -q '404'; then
				printf "User does not exist"
			else
					mpv https://chaturbate.com/$2/
			fi
		else
			printf "Please enter a Chaturbate user"
		fi
	;;
	-d | --download)
		if [ "$2" != "" ]; then
			if curl -s -o /dev/null -w "%{http_code}" https://chaturbate.com/$2/ | grep -q '404'; then
				printf "User does not exist"
			else
				yt-dlp https://chaturbate.com/$2/
			fi
		else
			printf "Please specify a live stream to download"
		fi
	;;
	-s | --subscribe)
		if [ "$2" != "" ]; then
			printf "Function not implemented yet"
		else
			printf "Function not implemented yet"
		fi
	;;
	-h | --help)
		usage
	;;
	esac
fi
