#!/bin/bash

http_code=$(curl -s -o /dev/null -w "%{http_code}" https://chaturbate.com/$2/)

function usage() {
	printf "
	Usage:
	  cb-cli [options] [arguments]

	Options:
	  -w, --watch
	    Watch a user thar is currently live
	  -d, --download
	    Download a stream from a user that is currently live
	  -s, --subscribe
	    Subscribe to a user
	  -o, --online
	    Show all subbed online users
	  -q, --query
	    Search for streams by tag
	  -c, --config
	    Source a different configuration file
	  -h, --help
	    Display this help message

	Configuration:
	  By default configuration is stored in
	  $HOME/.config/cb-cli/cb-cli.conf.

	  You can source a different configuration file with
	  the --config flag and specifying a file.
	  
	  Subscriptions are stored in $HOME/.config/cb-cli/subscriptions.conf
	\n"
}

if [ $# -eq 0 ]; then
	usage
	exit 1
fi

if [ "$1" != "" ]; then
	case $1 in
	-w | --watch)
		if [ "$2" != "" ]; then
			if [ "$http_code" = "404" ] || [ "$http_code" = "301" ]; then
				printf "User does not exist\n"
			else
				mpv https://chaturbate.com/$2/
			fi
		else
			printf "Please specify a live stream to watch\n"
		fi
	;;
	-d | --download)
		if [ "$2" != "" ]; then
			if [ "$http_code" = "404" ] || [ "$http_code" = "301" ]; then
				printf "User does not exist\n"
			else
				yt-dlp https://chaturbate.com/$2/
			fi
		else
			printf "Please specify a live stream to download\n"
		fi
	;;
	-s | --subscribe)
		if [ "$2" != "" ]; then
			if [ ! -d $HOME/.config/cb-cli ]; then
				if [ "$http_code" = "404" ] || [ "$http_code" = "301" ]; then
					printf "User does not exist\n"
				else
					mkdir $HOME/.config/cb-cli
				if [ ! -f $HOME/.config/cb-cli/subscriptions.conf ]; then
					touch $HOME/.config/cb-cli/subscriptions.conf
				fi
					grep -x "@$2" $HOME/.config/cb-cli/subscriptions.conf || echo "@$2" >> $HOME/.config/cb-cli/subscriptions.conf
				fi
			else
				if [ "$http_code" = "404" ] || [ "$http_code" = "301" ]; then
					printf "User does not exist\n"
				else
				if [ ! -f $HOME/.config/cb-cli/subscriptions.conf ]; then
					touch $HOME/.config/cb-cli/subscriptions.conf
				fi
					grep -x "@$2" $HOME/.config/cb-cli/subscriptions.conf || echo "@$2" >> $HOME/.config/cb-cli/subscriptions.conf
				fi
			fi
		else
			printf "Please specify a user to subscribe to\n"
		fi
	;;
	-h | --help)
		usage
	;;
	esac
fi
